appname="云音乐歌词导出"
appver="1.1"
appcode="1"
appsdk="15"
path_pattern=""
packagename="com.zfn.exportlrc"
theme="Theme_DeviceDefault_Light_NoActionBar"
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
